// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolrTS.Database;

namespace SolrTS.Migrations
{
    [DbContext(typeof(SolrContext))]
    partial class SolrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.2.20120.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SolrTS.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = "PX1",
                            Group = "Blue",
                            JoinDate = new DateTime(2020, 3, 26, 16, 57, 30, 712, DateTimeKind.Local).AddTicks(6384),
                            Name = "Kevin"
                        },
                        new
                        {
                            Id = "PX2",
                            Group = "Blue",
                            JoinDate = new DateTime(2020, 3, 25, 16, 57, 30, 716, DateTimeKind.Local).AddTicks(3474),
                            Name = "Chris"
                        },
                        new
                        {
                            Id = "PX3",
                            Group = "Red",
                            JoinDate = new DateTime(2020, 3, 24, 16, 57, 30, 716, DateTimeKind.Local).AddTicks(3509),
                            Name = "Claire"
                        },
                        new
                        {
                            Id = "PX4",
                            Group = "Blue",
                            JoinDate = new DateTime(2020, 3, 23, 16, 57, 30, 716, DateTimeKind.Local).AddTicks(3514),
                            Name = "Sophie"
                        },
                        new
                        {
                            Id = "PX5",
                            Group = "Red",
                            JoinDate = new DateTime(2020, 3, 22, 16, 57, 30, 716, DateTimeKind.Local).AddTicks(3517),
                            Name = "Katalin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
